version: '3.7'
services:
  pinot-quickstart:
    image: apachepinot/pinot
    command: "QuickStart -type batch"
    container_name: pinot
    restart: unless-stopped
    ports:
      - "2181:2181" # zookeeper
      - "8098:8098" # server
      - "8099:8099" # broker
      - "9000:9000" # controller
    environment:
      JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms1G -Xmx4G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-controller.log"
  pinot-superset:
    image: apachepinot/pinot-superset
    container_name: superset
    ports:
      - "8088:8088"